//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aurora {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aurora-deop.Aurora.Properties.UIText", typeof(UIText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Acc.
        /// </summary>
        internal static string @__Acc {
            get {
                return ResourceManager.GetString("__Acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   tons.
        /// </summary>
        internal static string @__tons {
            get {
                return ResourceManager.GetString("__tons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albedo.
        /// </summary>
        internal static string Albedo {
            get {
                return ResourceManager.GetString("Albedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albedo Factor.
        /// </summary>
        internal static string AlbedoFactor {
            get {
                return ResourceManager.GetString("AlbedoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-GH Factor.
        /// </summary>
        internal static string AntiGHFactor {
            get {
                return ResourceManager.GetString("AntiGHFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti Green House Gas Pressure.
        /// </summary>
        internal static string AntiGreenHouseGasPressure {
            get {
                return ResourceManager.GetString("AntiGreenHouseGasPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aphelion.
        /// </summary>
        internal static string Aphelion {
            get {
                return ResourceManager.GetString("Aphelion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asteroids.
        /// </summary>
        internal static string Asteroids {
            get {
                return ResourceManager.GetString("Asteroids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atmosphere.
        /// </summary>
        internal static string Atmosphere {
            get {
                return ResourceManager.GetString("Atmosphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atmospheric Pressure.
        /// </summary>
        internal static string AtmosphericPressure {
            get {
                return ResourceManager.GetString("AtmosphericPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Temperature.
        /// </summary>
        internal static string BaseTemperature {
            get {
                return ResourceManager.GetString("BaseTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Type.
        /// </summary>
        internal static string BodyType {
            get {
                return ResourceManager.GetString("BodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string CanRetainAtmoSphereNo {
            get {
                return ResourceManager.GetString("CanRetainAtmoSphereNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string CanRetainAtmoSphereYes {
            get {
                return ResourceManager.GetString("CanRetainAtmoSphereYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to changes in climate, the dominant terrain on {0} has changed from {1} to {2}.
        /// </summary>
        internal static string ClimateChangeEventMsg {
            get {
                return ResourceManager.GetString("ClimateChangeEventMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colony Cost.
        /// </summary>
        internal static string ColonyCost {
            get {
                return ResourceManager.GetString("ColonyCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comets.
        /// </summary>
        internal static string Comets {
            get {
                return ResourceManager.GetString("Comets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Distance.
        /// </summary>
        internal static string CurrentDistance {
            get {
                return ResourceManager.GetString("CurrentDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This planet has a dangerous in its atmosphere and is not suitable as a homeworld.
        /// </summary>
        internal static string DangerousAtmosphereForHomeworld {
            get {
                return ResourceManager.GetString("DangerousAtmosphereForHomeworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density.
        /// </summary>
        internal static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        internal static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dust EffectiveAtm.
        /// </summary>
        internal static string DustEffectiveAtm {
            get {
                return ResourceManager.GetString("DustEffectiveAtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eccentricity.
        /// </summary>
        internal static string Eccentricity {
            get {
                return ResourceManager.GetString("Eccentricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aestusium.
        /// </summary>
        internal static string GasAestusium {
            get {
                return ResourceManager.GetString("GasAestusium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammonia.
        /// </summary>
        internal static string GasAmmonia {
            get {
                return ResourceManager.GetString("GasAmmonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argon.
        /// </summary>
        internal static string GasArgon {
            get {
                return ResourceManager.GetString("GasArgon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bromine.
        /// </summary>
        internal static string GasBromine {
            get {
                return ResourceManager.GetString("GasBromine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarbonDioxide.
        /// </summary>
        internal static string GasCarbonDioxide {
            get {
                return ResourceManager.GetString("GasCarbonDioxide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarbonMonoxide.
        /// </summary>
        internal static string GasCarbonMonoxide {
            get {
                return ResourceManager.GetString("GasCarbonMonoxide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chlorine.
        /// </summary>
        internal static string GasChlorine {
            get {
                return ResourceManager.GetString("GasChlorine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluorine.
        /// </summary>
        internal static string GasFluorine {
            get {
                return ResourceManager.GetString("GasFluorine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigusium.
        /// </summary>
        internal static string GasFrigusium {
            get {
                return ResourceManager.GetString("GasFrigusium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helium.
        /// </summary>
        internal static string GasHelium {
            get {
                return ResourceManager.GetString("GasHelium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrogen.
        /// </summary>
        internal static string GasHydrogen {
            get {
                return ResourceManager.GetString("GasHydrogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HydrogenSulfide.
        /// </summary>
        internal static string GasHydrogenSulfide {
            get {
                return ResourceManager.GetString("GasHydrogenSulfide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iodine.
        /// </summary>
        internal static string GasIodine {
            get {
                return ResourceManager.GetString("GasIodine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.
        /// </summary>
        internal static string GasLiteral {
            get {
                return ResourceManager.GetString("GasLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methane.
        /// </summary>
        internal static string GasMethane {
            get {
                return ResourceManager.GetString("GasMethane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neon.
        /// </summary>
        internal static string GasNeon {
            get {
                return ResourceManager.GetString("GasNeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitrogen.
        /// </summary>
        internal static string GasNitrogen {
            get {
                return ResourceManager.GetString("GasNitrogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NitrogenDioxide.
        /// </summary>
        internal static string GasNitrogenDioxide {
            get {
                return ResourceManager.GetString("GasNitrogenDioxide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NitrogenOxide.
        /// </summary>
        internal static string GasNitrogenOxide {
            get {
                return ResourceManager.GetString("GasNitrogenOxide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string GasNone {
            get {
                return ResourceManager.GetString("GasNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxygen.
        /// </summary>
        internal static string GasOxygen {
            get {
                return ResourceManager.GetString("GasOxygen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SulfurDioxide.
        /// </summary>
        internal static string GasSulfurDioxide {
            get {
                return ResourceManager.GetString("GasSulfurDioxide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaterVapor.
        /// </summary>
        internal static string GasWaterVapor {
            get {
                return ResourceManager.GetString("GasWaterVapor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravity.
        /// </summary>
        internal static string Gravity {
            get {
                return ResourceManager.GetString("Gravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gravity of this planet is too low for it to serve as a homeworld (minimum required 0.1G).
        /// </summary>
        internal static string GravityTooLowForHomeworld {
            get {
                return ResourceManager.GetString("GravityTooLowForHomeworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenhouse Factor.
        /// </summary>
        internal static string GreenhouseFactor {
            get {
                return ResourceManager.GetString("GreenhouseFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green House Gas Pressure.
        /// </summary>
        internal static string GreenHouseGasPressure {
            get {
                return ResourceManager.GetString("GreenHouseGasPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydro Extent.
        /// </summary>
        internal static string HydroExtent {
            get {
                return ResourceManager.GetString("HydroExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrosphere.
        /// </summary>
        internal static string Hydrosphere {
            get {
                return ResourceManager.GetString("Hydrosphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to decreasing temperature the ice sheet on {0} has frozen, lowering the Albedo from {1} to {2}. This has caused a sudden temperature decrease from {3}C to {4}C..
        /// </summary>
        internal static string IceSheetFrozenEventMsg {
            get {
                return ResourceManager.GetString("IceSheetFrozenEventMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to increasing temperature the ice sheet on {0} has melted, raising the Albedo from {1} to {2}. This has caused a sudden temperature increase from {3}C to {4}C..
        /// </summary>
        internal static string IceSheetMeltEventMsg {
            get {
                return ResourceManager.GetString("IceSheetMeltEventMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclination.
        /// </summary>
        internal static string Inclination {
            get {
                return ResourceManager.GetString("Inclination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This planet has insufficient oxygen for it to serve as a homeworld (minimum required 0.05 atm).
        /// </summary>
        internal static string InsufficientOxygenForHomeworld {
            get {
                return ResourceManager.GetString("InsufficientOxygenForHomeworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This planet has insufficient water to serve as a homeworld (minimum required 20%).
        /// </summary>
        internal static string InsufficientWaterForHomeworld {
            get {
                return ResourceManager.GetString("InsufficientWaterForHomeworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Luminosity Key Count is {0}.
        /// </summary>
        internal static string LuminosityKeyCountErrMsg {
            get {
                return ResourceManager.GetString("LuminosityKeyCountErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass.
        /// </summary>
        internal static string Mass {
            get {
                return ResourceManager.GetString("Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Colony Cost.
        /// </summary>
        internal static string MaxColonyCost {
            get {
                return ResourceManager.GetString("MaxColonyCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameLiteral {
            get {
                return ResourceManager.GetString("NameLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoSurvey.
        /// </summary>
        internal static string NoSurvey {
            get {
                return ResourceManager.GetString("NoSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orbital Distance.
        /// </summary>
        internal static string OrbitalDistance {
            get {
                return ResourceManager.GetString("OrbitalDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perihelion.
        /// </summary>
        internal static string Perihelion {
            get {
                return ResourceManager.GetString("Perihelion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eldar.
        /// </summary>
        internal static string SpeciesNameEldar {
            get {
                return ResourceManager.GetString("SpeciesNameEldar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        internal static string SpeciesNameHuman {
            get {
                return ResourceManager.GetString("SpeciesNameHuman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precursor.
        /// </summary>
        internal static string SpeciesNamePrecursor {
            get {
                return ResourceManager.GetString("SpeciesNamePrecursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakhas - #{0}.
        /// </summary>
        internal static string SpeciesNameRakhas {
            get {
                return ResourceManager.GetString("SpeciesNameRakhas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Swarm.
        /// </summary>
        internal static string SpeciesNameStarSwarm {
            get {
                return ResourceManager.GetString("SpeciesNameStarSwarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Star Type Age Range ID {0} not found.
        /// </summary>
        internal static string StarTypeRangeIDNotFoundErrMsg {
            get {
                return ResourceManager.GetString("StarTypeRangeIDNotFoundErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SurfaceTemperature.
        /// </summary>
        internal static string SurfaceTemperature {
            get {
                return ResourceManager.GetString("SurfaceTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The surface temperature of this planet is too high for it to serve as a homeworld (maximum allowed 70C).
        /// </summary>
        internal static string SurfaceTemperatureTooHighForHomeworld {
            get {
                return ResourceManager.GetString("SurfaceTemperatureTooHighForHomeworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The surface temperature of this planet is too low for it to serve as a homeworld (minimum required -70C).
        /// </summary>
        internal static string SurfaceTemperatureTooLowForHomeworld {
            get {
                return ResourceManager.GetString("SurfaceTemperatureTooLowForHomeworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Report Format.
        /// </summary>
        internal static string SurveyReportFormat {
            get {
                return ResourceManager.GetString("SurveyReportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string SystemBodyPeriod {
            get {
                return ResourceManager.GetString("SystemBodyPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SurfaceTemperature.
        /// </summary>
        internal static string Tectonics {
            get {
                return ResourceManager.GetString("Tectonics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidal Lock.
        /// </summary>
        internal static string TidalLockLiteral {
            get {
                return ResourceManager.GetString("TidalLockLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string TidalLockYes {
            get {
                return ResourceManager.GetString("TidalLockYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes - M.
        /// </summary>
        internal static string TidalLockYesMoon {
            get {
                return ResourceManager.GetString("TidalLockYesMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100Y.
        /// </summary>
        internal static string TimeSpan100Y {
            get {
                return ResourceManager.GetString("TimeSpan100Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25Y.
        /// </summary>
        internal static string TimeSpan25Y {
            get {
                return ResourceManager.GetString("TimeSpan25Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5Y.
        /// </summary>
        internal static string TimeSpan5Y {
            get {
                return ResourceManager.GetString("TimeSpan5Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string TimeSpanMonth {
            get {
                return ResourceManager.GetString("TimeSpanMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter.
        /// </summary>
        internal static string TimeSpanQuarter {
            get {
                return ResourceManager.GetString("TimeSpanQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string TimeSpanWeek {
            get {
                return ResourceManager.GetString("TimeSpanWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string TimeSpanYear {
            get {
                return ResourceManager.GetString("TimeSpanYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This oxygen content of the atmosphere is too high for the planet to serve as a homeworld (maximum allowed 30%).
        /// </summary>
        internal static string TooMuchOxygenForHomeworld {
            get {
                return ResourceManager.GetString("TooMuchOxygenForHomeworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string VaporFormWater {
            get {
                return ResourceManager.GetString("VaporFormWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venusian.
        /// </summary>
        internal static string VenusianAtmosphere {
            get {
                return ResourceManager.GetString("VenusianAtmosphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
