using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.Linq;
using System.Windows.Forms;
using Aurora;

public partial class GClass0
{
    public int MaxGameID;
    public int MaxSystemID;
    public int MaxRuinRaceID;
    public int MaxSystemBodyID;
    public int MaxIncrementID;
    public int MaxStarID;
    public int MaxWarpPointID;
    public int int_7;
    public int int_8;
    public int int_9;
    public int int_10;
    public int int_11;
    public int int_12;
    public int int_13;
    public int int_14;
    public int int_15;
    public int int_16;
    public int int_17;
    public int int_18;
    public int int_19;
    public int int_20;
    public int int_21;
    public int int_22;
    public int int_23;
    public int int_24;
    public int int_25;
    public int int_26;
    public int int_27;
    public int int_28;
    public int int_29;
    public int int_30;
    public int int_31;
    public int int_32;
    public int int_33;
    public int int_34;
    public int int_35;
    public int int_36;
    public int int_37;
    public int int_38;
    public int int_39;
    public int int_40;
    public int int_41;
    public int int_42;
    public int int_43;
    public int int_44;
    public int int_45;
    public int MaxOrderTemplateID;
    public int int_47;
    public int int_48;
    public int int_49;
    public int int_50;
    public int int_51;
    public int int_52;
    public int int_53;
    public int int_54;
    public int int_55;
    public int int_56;
    private int int_57;
    private int int_58;
    public TechSystem gclass164_0;
    public ShipComponent gclass230_0;
    public ShipComponent gclass230_1;
    public RaceMissile gclass129_0;
    public GClass194 gclass194_0;
    public GroundUnitClass101 gclass101_0;
    public int int_59;
    public int int_60;
    public int int_61;
    public int int_62;
    public int int_63;
    public int int_64;
    public GClass92 gclass92_0;
    public TacticalMap tacticalMap_0;
    public Dictionary<int, NavalAdminCommand> NavalAdminCommands = new Dictionary<int, NavalAdminCommand>();
    public Dictionary<int, FleetData> FleetDictionary = new Dictionary<int, FleetData>();
    public Dictionary<int, SubFleet> SubFleetDictionary = new Dictionary<int, SubFleet>();
    public Dictionary<int, GClass22> dictionary_3 = new Dictionary<int, GClass22>();
    public Dictionary<int, FCTShipData40> FCTShipDataDictionary = new Dictionary<int, FCTShipData40>();
    public Dictionary<int, RaceMissile> RaceMissileDictionary = new Dictionary<int, RaceMissile>();
    public Dictionary<int, GClass132> dictionary_6 = new Dictionary<int, GClass132>();
    public Dictionary<int, FCTMassDriverPacket126> MassDriverPacketsDictionary = new Dictionary<int, FCTMassDriverPacket126>();
    public Dictionary<int, ShippingLineData> ShippingLineDictionary = new Dictionary<int, ShippingLineData>();
    public Dictionary<int, SystemData200> SystemDataDictionary = new Dictionary<int, SystemData200>();
    public Dictionary<int, Star197> StarDictionary = new Dictionary<int, Star197>();
    public Dictionary<int, SystemBodyData> SystemBodyRecordDic = new Dictionary<int, SystemBodyData>();
    public Dictionary<int, JumpPoint120> JumpPointDictionary = new Dictionary<int, JumpPoint120>();
    public Dictionary<int, GClass214> dictionary_13 = new Dictionary<int, GClass214>();
    public Dictionary<int, GClass212> dictionary_14 = new Dictionary<int, GClass212>();
    public Dictionary<int, GClass211> dictionary_15 = new Dictionary<int, GClass211>();
    public Dictionary<int, GClass210> dictionary_16 = new Dictionary<int, GClass210>();

    public Dictionary<int, DIMKnownSystemsData198> KnownSystemDataDictionary =
        new Dictionary<int, DIMKnownSystemsData198>();

    public Dictionary<int, DIMKnownSystemsData198> dictionary_18 = new Dictionary<int, DIMKnownSystemsData198>();
    public List<SystemBodyData> list_0 = new List<SystemBodyData>();
    public Dictionary<MoveActionType, MoveActionDefinition> MoveActionDictionary = new Dictionary<MoveActionType, MoveActionDefinition>();
    public Dictionary<AuroraStandingOrder, StandingOrderDefinition> StandingOrderDictionary = new Dictionary<AuroraStandingOrder, StandingOrderDefinition>();

    public Dictionary<AuroraFleetCondition, FleetConditionDefinition>
        FleetConditionDictionary = new Dictionary<AuroraFleetCondition, FleetConditionDefinition>();

    public Dictionary<int, PopulationData> PopulationDataDictionary = new Dictionary<int, PopulationData>();
    public Dictionary<AtmosphericGas, AtmosphericGasDefinition> AtmosphericGasDictionary = new Dictionary<AtmosphericGas, AtmosphericGasDefinition>();
    public Dictionary<int, ShipHull> ShipHullDictionary = new Dictionary<int, ShipHull>();
    public Dictionary<int, StellarType> StarTypeDictionary = new Dictionary<int, StellarType>();
    public Dictionary<int, RuinRaceData> RuinRaceDictionary = new Dictionary<int, RuinRaceData>();
    public Dictionary<int, GClass220> dictionary_27 = new Dictionary<int, GClass220>();
    public Dictionary<int, GClass65> dictionary_28 = new Dictionary<int, GClass65>();
    public Dictionary<int, GClass233> dictionary_29 = new Dictionary<int, GClass233>();
    public Dictionary<int, GClass59> dictionary_30 = new Dictionary<int, GClass59>();
    public Dictionary<int, GClass193> dictionary_31 = new Dictionary<int, GClass193>();
    public Dictionary<int, GClass192> dictionary_32 = new Dictionary<int, GClass192>();
    public Dictionary<int, OrderTemplateData> MoveOrderTemplateDictionary = new Dictionary<int, OrderTemplateData>();
    public Dictionary<int, FCTRaceMedalRecord> RaceMedalDictionary = new Dictionary<int, FCTRaceMedalRecord>();
    public Dictionary<int, MedalCondition> MedalConditionDictionary = new Dictionary<int, MedalCondition>();
    public List<GClass44> list_1 = new List<GClass44>();
    public Dictionary<int, GameRace> FCTRaceRecordDic = new Dictionary<int, GameRace>();
    public Dictionary<int, GClass194> SpeciesDictionary = new Dictionary<int, GClass194>();
    public Dictionary<int, RuinDefinition> RuinDefinitionDictionary = new Dictionary<int, RuinDefinition>();
    public Dictionary<PopPoliticalStatusType, PopulationPoliticalStatus> PopulationPoliticalStatusDictionary = new Dictionary<PopPoliticalStatusType, PopulationPoliticalStatus>();
    public Dictionary<int, RankTheme> RankThemeDictionary = new Dictionary<int, RankTheme>();
    public Dictionary<OperationalGroupID, OperationalGroup> OperationalGroupDictionary = new Dictionary<OperationalGroupID, OperationalGroup>();
    public List<GClass12> list_2 = new List<GClass12>();
    public List<DIMDesignPhilosophyTechProgression> DesignPhilosophyTechProgressionsDictionary = new List<DIMDesignPhilosophyTechProgression>();
    public List<GClass16> list_4 = new List<GClass16>();
    public Dictionary<int, GClass55> dictionary_42 = new Dictionary<int, GClass55>();
    public Dictionary<int, GClass55> dictionary_43 = new Dictionary<int, GClass55>();

    public Dictionary<AuroraInstallationType, PlanetaryInstallationType> PlanetaryInstallationDictionary =
        new Dictionary<AuroraInstallationType, PlanetaryInstallationType>();

    public Dictionary<WealthUsage, WealthUsageData> WealthUsageDictionary = new Dictionary<WealthUsage, WealthUsageData>();

    public Dictionary<EventType, DIMEventTypeData88> DIMEventTypeDictionary =
        new Dictionary<EventType, DIMEventTypeData88>();

    public Dictionary<int, CommanderNameThemeData> NameThemeDictionary = new Dictionary<int, CommanderNameThemeData>();
    public Dictionary<AuroraResearchField, ResearchFieldData> ResearchFieldDictionary = new Dictionary<AuroraResearchField, ResearchFieldData>();
    public Dictionary<TechType, TechTypeData> TechTypeDataDictionary = new Dictionary<TechType, TechTypeData>();
    public Dictionary<int, TechSystem> TechDataDictionary = new Dictionary<int, TechSystem>();
    public Dictionary<MineralUsage, MineralUsageData> MineralUsageDataDictionary = new Dictionary<MineralUsage, MineralUsageData>();
    public Dictionary<AuroraComponentType, ComponentTypeData> ComponentTypeDictionary = new Dictionary<AuroraComponentType, ComponentTypeData>();
    public Dictionary<ClassSummaryTypeID, ClassSummaryType> ClassSummaryTypeDictionary = new Dictionary<ClassSummaryTypeID, ClassSummaryType>();
    public Dictionary<int, ShipComponent> ComponentDataDictionary = new Dictionary<int, ShipComponent>();
    public Dictionary<int, NamingTheme> ThemeDictionary = new Dictionary<int, NamingTheme>();
    public Dictionary<int, TradeGoodsDefinition> TradeGoodsDictionary = new Dictionary<int, TradeGoodsDefinition>();
    public Dictionary<SystemAgeID, SystemAge> SystemAgeDictionary = new Dictionary<SystemAgeID, SystemAge>();
    public Dictionary<int, SystemAbundance> SystemAbundanceDictionary = new Dictionary<int, SystemAbundance>();
    public Dictionary<int, TraitGroup> TraitGroupDictionary = new Dictionary<int, TraitGroup>();
    public Dictionary<int, string> TraitNameDictionary = new Dictionary<int, string>();
    public Dictionary<int, AssignmentTypeFilter> AssignmentTypeFilterDictionary = new Dictionary<int, AssignmentTypeFilter>();
    public Dictionary<CommanderBonusType, CommanderBonus> CommanderBonusDictionary = new Dictionary<CommanderBonusType, CommanderBonus>();
    public Dictionary<AutomatedClassDesignType, AutomatedClassDesign> AutomatedClassDesignDictionary = new Dictionary<AutomatedClassDesignType, AutomatedClassDesign>();
    public Dictionary<ResearchCategoryType, ResearchCategoryData> ResearchCategoryDictionary = new Dictionary<ResearchCategoryType, ResearchCategoryData>();
    public Dictionary<AdminCommandType, NavalAdminCommandType> AdminCommandTypeDictionary = new Dictionary<AdminCommandType, NavalAdminCommandType>();
    public List<GClass159> list_5 = new List<GClass159>();
    public List<AcidAttack> AcidAttackList = new List<AcidAttack>();
    public List<TechSystem> list_7 = new List<TechSystem>();
    public Dictionary<GroundUnitBaseType, GroundUnitBaseTypeData> GroundUnitBaseTypeDictionary = new Dictionary<GroundUnitBaseType, GroundUnitBaseTypeData>();
    public Dictionary<int, ArmourTypeData> ArmourTypeDictionary = new Dictionary<int, ArmourTypeData>();
    public Dictionary<GroundUnitComponent, GroundComponentTypeDefinition> GroundUnitComponentDataDictionary = new Dictionary<GroundUnitComponent, GroundComponentTypeDefinition>();
    public Dictionary<GroundUnitCapability, GroundUnitCapabilityDefinition> GroundUnitCapabilityDictionary = new Dictionary<GroundUnitCapability, GroundUnitCapabilityDefinition>();
    public Dictionary<int, GroundUnitClass101> GroundUnitClassDictionary = new Dictionary<int, GroundUnitClass101>();
    public Dictionary<int, GroundUnitFormationData> FormationDictionary = new Dictionary<int, GroundUnitFormationData>();
    public Dictionary<int, GroundUnitFormationTemplateData> FormationTemplateRecordDic = new Dictionary<int, GroundUnitFormationTemplateData>();

    public Dictionary<PlanetDominantTerrain, PlanetaryTerrainDefinition>
        DominantTerrainTypeDictionary = new Dictionary<PlanetDominantTerrain, PlanetaryTerrainDefinition>();

    public Dictionary<AutomatedGroundTemplateDesignType, AutomatedGroundTemplateDesign> AutoGroundTemplateDesignsDictionary = new Dictionary<AutomatedGroundTemplateDesignType, AutomatedGroundTemplateDesign>();

    public Dictionary<int, ShipClassTemplate184> ShipClassTemplateDictionary =
        new Dictionary<int, ShipClassTemplate184>();

    public Dictionary<int, GClass185> dictionary_76 = new Dictionary<int, GClass185>();
    public List<GClass172> list_8 = new List<GClass172>();
    public List<GClass215> list_9 = new List<GClass215>();
    public List<GClass216> list_10 = new List<GClass216>();
    public List<HideEventData> HideEventList = new List<HideEventData>();
    public List<string> RaceTitleList = new List<string>();
    public List<string> LineNameList = new List<string>();
    public List<CommanderNameDefinition> CommanderNameList = new List<CommanderNameDefinition>();
    public List<CompanyNameData> CompanyNameList = new List<CompanyNameData>();
    public List<string> MiningNameList = new List<string>();
    public List<string> ShipyardCompanySuffixList = new List<string>();
    public List<AtmosphericPreset> AtmosphericPresetList = new List<AtmosphericPreset>();
    public List<GClass141> EmpireTitleNameList = new List<GClass141>();
    public List<GClass121> list_20 = new List<GClass121>();
    public List<GClass176> list_21 = new List<GClass176>();
    public List<GClass37> list_22 = new List<GClass37>();
    public List<FCTShipData40> list_23 = new List<FCTShipData40>();
    public Dictionary<string, WindowPosition207> WindowPositionDictionary = new Dictionary<string, WindowPosition207>();
    public List<GClass222> list_24 = new List<GClass222>();
    public List<SystemData200> list_25 = new List<SystemData200>();
    public List<GClass66> list_26 = new List<GClass66>();
    public List<GClass67> list_27 = new List<GClass67>();
    public List<GClass67> list_28 = new List<GClass67>();
    public List<GClass68> list_29 = new List<GClass68>();
    public List<GroundUnitFormationElement> list_30 = new List<GroundUnitFormationElement>();
    public GameRace raceRecord_0;
    public DIMKnownSystemsData198 gclass198_0;
    public SystemBodyData gclass1_0;
    public GEnum30 SolDisaster;
    public NamingTheme gclass140_0;
    public int EldarOpGroupProgression;
    public bool bool_0;
    public bool bool_1;
    public bool bool_2;
    public bool bool_3;
    public int GameID;
    public int DifficultyModifier;
    public int NumberOfSystems;
    public int StartYear;
    public int LocalSystemChance;
    public int LocalSystemSpread;
    public int MinConstructionPeriod;
    public int MinGroundCombatPeriod = 28800;
    public int RaceChance;
    public int RaceChanceNPR;
    public int NewRuinCreationChance;
    public int CivilianShippingLinesActive;
    public int AllowCivilianHarvesters;
    public int MinComets;
    public int OrbitalMotion;
    public int OrbitalMotionAst;
    public int PoliticalAdmirals;
    public int DefaultRaceID;
    public int ConstellationNames = 1;
    public int StarEccentricity = 1;
    public int GasGiantEffects = 1;
    public int InexpFleets;
    public int AutoJumpGates;
    public int Precursors;
    public int Rakhas;
    public int Eldar;
    public int StarSwarm;
    public int Invaders;
    public int GenerateNPRs;
    public int HumanNPRs;
    public int GenerateNonTNOnly;
    public int NoOverhauls;
    public int RealisticPromotions;
    public int UseKnownStars;
    public int NonPlayerSystemDetection;
    public int NPRsGenerateSwarm;
    public int NPRsGeneratePrecursors;
    public int NPRsGenerateRifts;
    public int NPRsEncounterRaiders;
    public int TechFromConquest;
    public int ResearchSpeed;
    public int TerraformingSpeed;
    public int SurveySpeed;
    public int MaxEventDays = 60;
    public int MaxEventCount = 300;
    public int SwarmSystems;
    public int InvaderSystems;
    public int RaiderSystems;
    public int LimitedLabs;
    public int OneSecondSubPulse;
    public int HostilityModifier;
    public int MinorRaceChance = 20;
    public int PreIndustrialChance = 10;
    public int ConventionalChance = 10;
    public int LimitPlanetaryDistance = 1;
    public int ParallelUniverse;
    public int UseThemeInKnownStars;
    public int EnhancedInvaders;
    public int EnhancedSwarm;
    public int EnhancedPrecursors;
    public int SwarmInvasion;
    public int NPRBaseTransits;
    public int NPRRandomTransits;
    public int NPRMaxSystems;
    public int MinimumSwarmRP = 600000;
    public bool chkOrders;
    public bool chkOverhauls;
    public bool chkShowJD;
    public Decimal GameTime;
    public Decimal LastGrowthTime;
    public Decimal LastGroundCombatTime;
    public Decimal decimal_3;
    public Decimal decimal_4;
    public Decimal PlayerExplorationTime;
    public Decimal TruceCountdown;
    public Decimal decimal_7;
    public Decimal decimal_8;
    public Decimal decimal_9 = 1M;
    public Decimal StartTimeEldar;
    public Decimal StartTimeSwarm;
    public Decimal StartTimeInvaders;
    public string SMPassword;
    public string GameName;
    public bool bool_7;
    public bool bool_8;
    public bool bool_9;
    public bool bool_10;
    public bool bool_11;
    public bool bool_12;
    public bool bool_13;
    public bool bool_14;
    public bool CurrentGroundCombat;
    public bool bool_16;
    public bool bool_17;
    public bool bool_18;
    public bool bool_19;
    public bool bool_20;
    public int int_131 = 5;
    public int SubPulseLength;
    public int int_133;
    public double double_0;
    public double double_1;
    public double double_2;
    public double double_3;
    public double double_4;
    public double double_5;
    public double double_6;
    public double double_7;
    public int int_134;
    public int int_135;
    public string string_2;
    public List<AuroraCommandType> list_31 = new List<AuroraCommandType>();
    public List<string> list_32 = new List<string>();
    public FCTRaceMedalRecord gclass42_0;
    public CheckState checkState_0;
    public CheckState checkState_1;
    public CheckState checkState_2;
    public PopulationData gclass146_0;
    public string string_3;
    public string string_4;
    public string string_5;
    public string string_6;
    public string string_7 = "";
    public string string_8 = "";
    public string string_9 = "";
    public bool bool_21;
    public object object_0;
    public bool bool_22;
    public bool bool_23;
    public GameRace gclass21_1;
    public FleetData gclass85_0;
    public bool bool_24 = true;
}